/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author padol
 */
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.*;
import java.util.Arrays;
import javax.swing.*;
import java.security.GeneralSecurityException;
import java.io.IOException;

public class Login extends javax.swing.JFrame {
    public static SheetsQuickstart sqs = new SheetsQuickstart();;
    public static String currentUser;
    public static boolean isAdmin = false;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Notiforsmth.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new JPanel();
        LOGOPanel = new javax.swing.JPanel();
        CRRLogo = new javax.swing.JLabel();
        crrDescription = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        loginButton = new RoundedButton("Login",5);
        registerButton = new RoundedButton("Register",5);
        InputPanel = new javax.swing.JPanel();
        UserField = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPanel();
        userLabel1 = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        Notiforsmth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainPanel.setBackground(new java.awt.Color(216, 216, 216));
        mainPanel.setForeground(new java.awt.Color(204, 204, 204));
        mainPanel.setPreferredSize(new java.awt.Dimension(400, 400));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGOPanel.setOpaque(false);
        LOGOPanel.setLayout(new java.awt.BorderLayout(10, 10));

        CRRLogo.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        CRRLogo.setForeground(new java.awt.Color(204, 102, 0));
        CRRLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CRRLogo.setText("CRR");
        CRRLogo.setToolTipText("");
        CRRLogo.setMaximumSize(new java.awt.Dimension(50, 50));
        CRRLogo.setMinimumSize(new java.awt.Dimension(50, 50));
        LOGOPanel.add(CRRLogo, java.awt.BorderLayout.CENTER);

        crrDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        crrDescription.setForeground(new java.awt.Color(204, 102, 0));
        crrDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crrDescription.setText("Creative Room Reservation"); // NOI18N
        LOGOPanel.add(crrDescription, java.awt.BorderLayout.PAGE_END);

        mainPanel.add(LOGOPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 44, 300, -1));

        ButtonPanel.setOpaque(false);
        ButtonPanel.setLayout(new java.awt.GridLayout(1, 0, 60, 0));

        loginButton.setBackground(new java.awt.Color(218, 218, 218));
        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.setPreferredSize(new java.awt.Dimension(100, 40));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(loginButton);

        registerButton.setBackground(new java.awt.Color(51, 51, 51));
        registerButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(204, 204, 204));
        registerButton.setText("Register");
        registerButton.setPreferredSize(new java.awt.Dimension(100, 40));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(registerButton);

        mainPanel.add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 331, 300, -1));

        InputPanel.setOpaque(false);
        InputPanel.setLayout(new java.awt.BorderLayout(0, 10));

        UserField.setOpaque(false);
        UserField.setLayout(new java.awt.BorderLayout(20, 5));

        userLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(51, 51, 51));
        userLabel.setText("Username");
        UserField.add(userLabel, java.awt.BorderLayout.CENTER);

        userField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userField.setForeground(new java.awt.Color(51, 51, 51));
        userField.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        UserField.add(userField, java.awt.BorderLayout.PAGE_END);

        InputPanel.add(UserField, java.awt.BorderLayout.PAGE_START);

        PasswordField.setOpaque(false);
        PasswordField.setLayout(new java.awt.BorderLayout(20, 5));

        userLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        userLabel1.setForeground(new java.awt.Color(51, 51, 51));
        userLabel1.setText("Password");
        PasswordField.add(userLabel1, java.awt.BorderLayout.PAGE_START);

        InputPanel.add(PasswordField, java.awt.BorderLayout.CENTER);

        mainPanel.add(InputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 152, 300, -1));

        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });
        mainPanel.add(PassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 300, 30));

        Notiforsmth.setForeground(new java.awt.Color(255, 0, 0));
        Notiforsmth.setLabelFor(Notiforsmth);
        Notiforsmth.setText("This is Noti");
        Notiforsmth.setToolTipText("");
        Notiforsmth.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.add(Notiforsmth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.ipady = 73;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(150, 300, 150, 300);
        getContentPane().add(mainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String userID = userField.getText();
        String password = String.valueOf(PassField.getPassword());
        String find = sqs.searchWithQuery("Sheet2", "A", userID);
            if(!find.equals("NOT FOUND")&&find!=null){
                if (find.equals(sqs.searchWithQuery("Sheet2", "B", password))) {
                    String role = sqs.getByIndexandColumn(find,"C");
                    System.out.println("Debug - Role for " + userID + ": " + role); // สำหรับตรวจสอบ

                    if (role != null) {
                        Login.isAdmin = "admin".equals(role);
                    } else {
                        Login.isAdmin = false; // กำหนดค่าเริ่มต้นหาก role เป็น null
                    }
                    currentUser = userID;
                    try {
                Logger.getInstance().log(userID, "LOGIN",userID + " has logged in.");
                }
                catch (GeneralSecurityException | IOException ex) {
                    ex.printStackTrace();
                }
                    dispose();
                    mainbookingpage mainpage = new mainbookingpage();
                    mainpage.setVisible(true);
                }
                else {
                    Notiforsmth.setForeground(Color.red);
                    Notiforsmth.setText("Wrong Password");
                    Notiforsmth.setVisible(true);
                }
            }
            else {
                Notiforsmth.setForeground(Color.red);
                Notiforsmth.setText("username not found");
                Notiforsmth.setVisible(true);
            }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String userID = userField.getText();
        String password = String.valueOf(PassField.getPassword());

        if (userID.length() >= 6 && password.length() >= 6) {
            String find = sqs.searchWithQuery("Sheet2", "A", userID);
            String findpass = sqs.searchWithQuery("Sheet2", "B", password);

            if (find.equals("NOT FOUND") && findpass.equals("NOT FOUND")) {
                // เพิ่ม role "user" ในคอลัมน์ C โดยอัตโนมัติ
                java.util.List<java.util.List<Object>> newData = Arrays.asList(
                        Arrays.asList(userID, password, "user") // <-- เพิ่ม "user" ในคอลัมน์ C
                );

                sqs.createData("Sheet2!A2", newData);

                Notiforsmth.setForeground(Color.green);
                Notiforsmth.setText("Register successful");
                Notiforsmth.setVisible(true);
                userField.setText("");
                PassField.setText("");
                try {
                Logger.getInstance().log(userID, "ACCOUNT", "Account " + userID + " has been created.");
                }
                catch (GeneralSecurityException | IOException ex) {
                    ex.printStackTrace();
                }
            } else {
                Notiforsmth.setForeground(Color.red);
                Notiforsmth.setText("Username or password already exists");
                Notiforsmth.setVisible(true);
            }
        } else {
            Notiforsmth.setForeground(Color.red);
            Notiforsmth.setText("Username and password must be at least 6 characters");
            Notiforsmth.setVisible(true);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonMouseClicked

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowActivated

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldActionPerformed

    
    public class RoundedButton extends JButton {
        private int radius; // Corner radius

        public RoundedButton(String text, int radius) {
            super(text);
            this.radius = radius;
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            // Draw button background as a rounded rectangle
            g2.setColor(getBackground()); 
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);

            super.paintComponent(g); // Paint button text
            g2.dispose();
        }

        @Override
        protected void paintBorder(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            // Draw border with rounded edges
            g2.setColor(getForeground());
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, radius, radius);

            g2.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf()); // Change to FlatLightLaf, FlatIntelliJLaf, etc.
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JLabel CRRLogo;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel LOGOPanel;
    private javax.swing.JLabel Notiforsmth;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JPanel PasswordField;
    private javax.swing.JPanel UserField;
    private javax.swing.JLabel crrDescription;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userLabel1;
    // End of variables declaration//GEN-END:variables
}
