/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.*;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.util.*;
import javax.swing.*;
import javax.swing.Timer;

public class Reservation extends javax.swing.JFrame {

    private String name;
    private java.util.List<java.util.List<Object>> data;
    private java.util.List<java.util.List<Object>> databook;

    /**
     * Creates new form NewJFrame1
     */
    public Reservation(String nameroom) {
        name = nameroom;
        initComponents();
        setLocation(300, 50);
        room.setText(room.getText() + " " + name);
        checkBookingStatus();

        Timer timer = new Timer(60000, e -> checkBookingStatus());
        timer.start();
    }

    private Reservation() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void checkBookingStatus() {
        SheetsQuickstart sqs = Login.sqs;
        int currentDay = Integer.parseInt(date.getCurrentDayofyear());

        // ตรวจสอบสถานะการจองแต่ละช่วงเวลา
        updateTimeSlotStatus(Butto89, 2, currentDay, sqs);
        updateTimeSlotStatus(jButton910, 3, currentDay, sqs);
        updateTimeSlotStatus(jButton1011, 4, currentDay, sqs);
        updateTimeSlotStatus(jButton1112, 5, currentDay, sqs);
        updateTimeSlotStatus(jButton01, 6, currentDay, sqs);
        updateTimeSlotStatus(jButton12, 7, currentDay, sqs);
        updateTimeSlotStatus(jButton23, 8, currentDay, sqs);
        updateTimeSlotStatus(jButton34, 9, currentDay, sqs);
        updateTimeSlotStatus(jButton45, 10, currentDay, sqs);
        updateTimeSlotStatus(jButton56, 11, currentDay, sqs);
    }

    private void updateTimeSlotStatus(JButton button, int row, int currentDay, SheetsQuickstart sqs) {
        try {
            java.util.List<java.util.List<Object>> data = sqs.readData("room" + name + "!B" + row + ":D" + row);

            if (data != null && !data.isEmpty() && data.get(0).size() >= 3) {
                String status = data.get(0).get(0).toString();
                int bookingDate = Integer.parseInt(data.get(0).get(1).toString());
                String userId = data.get(0).get(2).toString();

                if (status.equalsIgnoreCase("used") && bookingDate == currentDay) {
                    button.setBackground(new Color(249, 102, 102));
                    button.setToolTipText("Booked by: " + userId);
                } else {
                    button.setBackground(new Color(119, 255, 119));
                    button.setToolTipText("Available");
                }
            } else {
                button.setBackground(new Color(119, 255, 119));
                button.setToolTipText("Available");
            }
        } catch (Exception e) {
            button.setBackground(Color.YELLOW);
            button.setForeground(Color.BLACK);
            button.setToolTipText("Error checking status");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        room = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Butto89 = new javax.swing.JButton();
        jButton910 = new javax.swing.JButton();
        jButton1112 = new javax.swing.JButton();
        jButton1011 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton01 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton45 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        room.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        room.setForeground(new java.awt.Color(255, 255, 255));
        room.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        room.setText("Room");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(room, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Butto89.setBackground(new java.awt.Color(255, 204, 153));
        Butto89.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Butto89.setForeground(new java.awt.Color(51, 51, 51));
        Butto89.setText("08:00AM-09:00AM");
        Butto89.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        Butto89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butto89ActionPerformed(evt);
            }
        });

        jButton910.setBackground(new java.awt.Color(255, 204, 153));
        jButton910.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton910.setForeground(new java.awt.Color(51, 51, 51));
        jButton910.setText("09:00AM-10:00AM");
        jButton910.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        jButton910.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton910ActionPerformed(evt);
            }
        });

        jButton1112.setBackground(new java.awt.Color(255, 204, 153));
        jButton1112.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1112.setForeground(new java.awt.Color(51, 51, 51));
        jButton1112.setText("11:00AM-12:00PM");
        jButton1112.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        jButton1112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1112ActionPerformed(evt);
            }
        });

        jButton1011.setBackground(new java.awt.Color(255, 204, 153));
        jButton1011.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1011.setForeground(new java.awt.Color(51, 51, 51));
        jButton1011.setText("10:00AM-11:00AM");
        jButton1011.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        jButton1011.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1011ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Butto89, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton910, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1011, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1112, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Butto89, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton910, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1011, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1112, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jButton01.setBackground(new java.awt.Color(255, 204, 153));
        jButton01.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton01.setForeground(new java.awt.Color(51, 51, 51));
        jButton01.setText("12:00PM-01:00PM");
        jButton01.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        jButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton01ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 204, 153));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 51, 51));
        jButton12.setText("01:00PM-02:00PM");
        jButton12.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton34.setBackground(new java.awt.Color(255, 204, 153));
        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(51, 51, 51));
        jButton34.setText("03:00PM-04:00PM");
        jButton34.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(255, 204, 153));
        jButton23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(51, 51, 51));
        jButton23.setText("02:00PM-03:00PM");
        jButton23.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jButton45.setBackground(new java.awt.Color(255, 204, 153));
        jButton45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton45.setForeground(new java.awt.Color(51, 51, 51));
        jButton45.setText("04:00PM-05:00PM");
        jButton45.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });

        jButton56.setBackground(new java.awt.Color(255, 204, 153));
        jButton56.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton56.setForeground(new java.awt.Color(51, 51, 51));
        jButton56.setText("05:00PM-06:00PM");
        jButton56.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true)));
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Butto89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butto89ActionPerformed
        booking(0, 2);
    }//GEN-LAST:event_Butto89ActionPerformed

    private void jButton910ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton910ActionPerformed
        booking(1, 3);
    }//GEN-LAST:event_jButton910ActionPerformed

    private void jButton1112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1112ActionPerformed
        booking(3, 5);
    }//GEN-LAST:event_jButton1112ActionPerformed

    private void jButton1011ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1011ActionPerformed
        booking(2, 4);
    }//GEN-LAST:event_jButton1011ActionPerformed

    private void jButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton01ActionPerformed
        booking(4, 6);
    }//GEN-LAST:event_jButton01ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        booking(5, 7);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        booking(7, 9);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        booking(6, 8);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        booking(8, 10);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        booking(9, 11);
    }//GEN-LAST:event_jButton56ActionPerformed
    public void booking(int timeSlotIndex, int rowToUpdate) {
        try {
            // 1. ตรวจสอบค่าอินพุต
            if (timeSlotIndex < 0 || timeSlotIndex > 9) { // มี 10 ช่วงเวลา (0-9)
                JOptionPane.showMessageDialog(null, "Invalid time slot selected", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. อ่านข้อมูลการจองจาก Google Sheets
            databook = Login.sqs.readData("room" + name + "!B2:D11");

            if (databook == null || databook.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Failed to load booking data", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. ตรวจสอบว่าช่วงเวลานี้ว่างหรือไม่
            java.util.List<Object> timeSlotData = databook.get(timeSlotIndex);
            if (timeSlotData == null || timeSlotData.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Time slot data not found", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String status = timeSlotData.get(0).toString();
            String bookingDate = timeSlotData.size() > 1 ? timeSlotData.get(1).toString() : "";
            String bookedBy = timeSlotData.size() > 2 ? timeSlotData.get(2).toString() : "";

            // 4. ตรวจสอบสถานะการจอง
            if ("no".equalsIgnoreCase(status) || status.isEmpty()) {
                // 5. จองห้อง
                String currentDate = date.getCurrentDayofyear();
                String currentUser = Login.currentUser;

                java.util.List<java.util.List<Object>> usedData = Arrays.asList(
                        Arrays.asList("used", currentDate, currentUser)
                        
                );

                // 6. อัพเดทข้อมูลใน Google Sheets
                boolean updateSuccess = Login.sqs.updateData(
                        "room" + name + "!B" + rowToUpdate + ":D" + rowToUpdate,
                        usedData
                );

                if (updateSuccess) {
                    // 7. อัพเดท UI
                    updateButtonStatus(timeSlotIndex, currentUser);
                    JOptionPane.showMessageDialog(null,
                            "Reservation successful for " + getTimeSlotName(timeSlotIndex),
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                    try {
                Logger.getInstance().log(Login.currentUser, "RESERVE",Login.currentUser + " has reserved a room.");
                }
                catch (GeneralSecurityException | IOException ex) {
                    ex.printStackTrace();
                }
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Failed to update reservation",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // แสดงข้อมูลการจองที่มีอยู่
                String bookedByUser = bookedBy.isEmpty() ? "unknown"
                        : bookedBy;
                JOptionPane.showMessageDialog(null,
                        "This time slot is already booked by: " + bookedByUser
                        + "\nBooking date: " + bookingDate,
                        "Already Booked",
                        JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "An error occurred: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

// เมธอดช่วยเหลือสำหรับอัพเดทสถานะปุ่ม
    private void updateButtonStatus(int timeSlotIndex, String bookedBy) {
        JButton button = getButtonByIndex(timeSlotIndex);
        if (button != null) {
            button.setBackground(new Color(249, 102, 102));
            button.setToolTipText("Booked by: " + bookedBy);
        }
    }

// เมธอดช่วยเหลือสำหรับหาปุ่มจาก index
    private JButton getButtonByIndex(int index) {
        switch (index) {
            case 0:
                return Butto89;
            case 1:
                return jButton910;
            case 2:
                return jButton1011;
            case 3:
                return jButton1112;
            case 4:
                return jButton01;
            case 5:
                return jButton12;
            case 6:
                return jButton23;
            case 7:
                return jButton34;
            case 8:
                return jButton45;
            case 9:
                return jButton56;
            default:
                return null;
        }
    }

// เมธอดช่วยเหลือสำหรับชื่อช่วงเวลา
    private String getTimeSlotName(int index) {
        String[] timeSlots = {
            "08:00-09:00", "09:00-10:00", "10:00-11:00", "11:00-12:00",
            "12:00-13:00", "13:00-14:00", "14:00-15:00", "15:00-16:00",
            "16:00-17:00", "17:00-18:00"
        };
        return (index >= 0 && index < timeSlots.length) ? timeSlots[index] : "Unknown time slot";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Butto89;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton1011;
    private javax.swing.JButton jButton1112;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton910;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel room;
    // End of variables declaration//GEN-END:variables
}
